# Batting Analysis of The World Cup 2019
> Inspired by some graphics made by [@SAAdvantage](https://twitter.com/SAAdvantage)

In [2]:
# Imports
import requests
import pandas as pd
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import re

Define the URL for the summary page that shows the overall batting stats for the top 50 highest scoring batsman at The World Cup 2019.

In [3]:
url = 'http://stats.espncricinfo.com/ci/engine/records/batting/most_runs_career.html?id=12357;type=tournament'
soup = BeautifulSoup(requests.get(url).text, features="html.parser")

In [4]:
for caption in soup.find_all('caption'):
    if caption.get_text() == 'Most runs':
        main_table = caption.find_parent(
            'table', {'class': 'engineTable'})

In [8]:
columns = [header.get_text() for header in main_table.find('thead').find_all('tr')[0].find_all('th')]
rows = []

for innings in [row for row in main_table.find('tbody').find_all('tr')]:
    rows.append([stat.get_text() for stat in innings.find_all('td')])
    
df_raw = pd.DataFrame(rows, columns=columns).apply(pd.to_numeric, errors='ignore')

In [10]:
df_raw.head()

,Player,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,RG Sharma (INDIA),9,9,1,648,140,81.00,659,98.33,5,1,0,67,14
1,DA Warner (AUS),10,10,1,647,166,71.88,724,89.36,3,3,0,66,8
2,Shakib Al Hasan (BDESH),8,8,1,606,124*,86.57,631,96.03,2,5,0,60,2
3,KS Williamson (NZ),10,9,2,578,148,82.57,771,74.96,2,2,0,50,3
4,JE Root (ENG),11,11,2,556,107,61.77,621,89.53,2,3,0,48,2

We don't need all the columns to work out what we are going to work out. We can use just those defined below.

In [18]:
df_trim = df_raw.loc[:, ['Player','Runs', 'BF','SR','4s','6s']].copy()

I'm going to define some cleaner functions just to handle the 'Player' column and split out the country into its own column.

In [36]:
def country(player_string):
    regex = re.compile(r'.* \(([A-Z]*)\)')
    return(regex.search(player_string).group(1))

def clean_player(player_string):
    regex = re.compile(r'([a-zA-Z ]*)\s\([A-Z]*\)')
    return(regex.search(player_string).group(1))

In [38]:
df_trim['Country'] = df_trim.Player.apply(country)
df_trim['Player'] = df_trim.Player.apply(clean_player)

In [39]:
df_trim

                  Player  Runs   BF      SR  4s  6s Country
0              RG Sharma   648  659   98.33  67  14   INDIA
1              DA Warner   647  724   89.36  66   8     AUS
2        Shakib Al Hasan   606  631   96.03  60   2   BDESH
3          KS Williamson   578  771   74.96  50   3      NZ
4                JE Root   556  621   89.53  48   2     ENG
5            JM Bairstow   532  573   92.84  67  11     ENG
6               AJ Finch   507  497  102.01  47  18     AUS
7             Babar Azam   474  540   87.77  50   2     PAK
8              BA Stokes   465  499   93.18  38  11     ENG
9                 JJ Roy   443  384  115.36  51  12     ENG
10               V Kohli   443  471   94.05  38   2   INDIA
11          F du Plessis   387  432   89.58  36   4      SA
12             SPD Smith   379  441   85.94  33   2     AUS
13              AT Carey   375  360  104.16  46   2     AUS
14            EJG Morgan   371  334  111.07  26  22     ENG
15       Mushfiqur Rahim   367  396   92.67  30   2   BDESH
16              N Pooran   367  366  100.27  33  10      WI
17              KL Rahul   361  466   77.46  31   5   INDIA
18           LRPL Taylor   350  465   75.26  29   2      NZ
19            UT Khawaja   316  358   88.26  30   1     AUS
20            JC Buttler   312  254  122.83  22   8     ENG
21     HE van der Dussen   311  344   90.40  14  10      SA
22                   Haq   305  400   76.25  31   1     PAK
23             Q de Kock   305  351   86.89  34   4      SA
24               SD Hope   274  389   70.43  21   3      WI
25           MDKJ Perera   273  246  110.97  32   1      SL
26              MS Dhoni   273  311   87.78  20   5   INDIA
27            SO Hetmyer   257  253  101.58  25   6      WI
28           Rahmat Shah   254  390   65.12  31   1     AFG
29       Mohammad Hafeez   253  285   88.77  22   5     PAK
30            AD Mathews   244  314   77.70  20   4      SL
31              CH Gayle   242  274   88.32  26  12      WI
32           Tamim Iqbal   235  328   71.64  25   0   BDESH
33           JDS Neesham   232  294   78.91  16   5      NZ
34     Najibullah Zadran   230  259   88.80  25   4     AFG
35             HH Pandya   226  201  112.43  21   4   INDIA
36       FDM Karunaratne   222  311   71.38  22   0      SL
37           Mahmudullah   219  244   89.75  14   5   BDESH
38          WIA Fernando   203  192  105.72  23   4      SL
39               HM Amla   203  313   64.85  16   0      SA
40          Haris Sohail   198  209   94.73  18   5     PAK
41  Hashmatullah Shahidi   197  349   56.44  20   2     AFG
42         Gulbadin Naib   194  243   79.83  20   2     AFG
43       C de Grandhomme   190  189  100.52  16   4      NZ
44          Fakhar Zaman   186  227   81.93  24   3     PAK
45            MJ Guptill   186  221   84.16  22   4      NZ
46             Liton Das   184  167  110.17  16   5   BDESH
47            GJ Maxwell   177  118  150.00  19   7     AUS
48             JO Holder   170  156  108.97  16   8      WI
49         Soumya Sarkar   166  164  101.21  24   2   BDESH